# Generated by Django 5.1.2 on 2024-10-09 06:53

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=products.models.EncryptedPriceField(max_length=12),
        ),
    ]
